package util;

/**
 * Created by Maciek on 2016-11-12.
 */
public class Vocabulary {

    public static String quantifiersWords =
            "much\n" +
            "a little\n" +
            "little\n" +
            "very little *\n" +
            "a bit of\n" +
            "a bit\n"+
            "a great deal of\n" +
            "a large amount of\n" +
            "a large quantity of\n"+
            "all\n" +
                    "enough\n" +
                    "more/most\n" +
                    "less/least\n" +
                    "no/none\n" +
                    "not any\n" +
                    "some\n" +
                    "any\n" +
                    "a lot of\n" +
                    "lots of\n" +
                    "plenty of\n"+
                    "many\n" +
                    "a few\n" +
                    "few\n" +
                    "very few **\n" +
                    "a number (of)\n" +
                    "several\n" +
                    "a large number of\n" +
                    "a great number of\n" +
                    "a majority of";

    public static String prepoistionWords = "aboard\n" +
            "about\n" +
            "above\n" +
            "across\n" +
            "after\n" +
            "against\n" +
            "along\n" +
            "amid\n" +
            "among\n" +
            "anti\n" +
            "around\n" +
            "as\n" +
            "at\n" +
            "before\n" +
            "behind\n" +
            "below\n" +
            "beneath\n" +
            "beside\n" +
            "besides\n" +
            "between\n" +
            "beyond\n" +
            "but\n" +
            "by\n" +
            "concerning\n" +
            "considering\n" +
            "despite\n" +
            "down\n" +
            "during\n" +
            "except\n" +
            "excepting\n" +
            "excluding\n" +
            "following\n" +
            "for\n" +
            "from\n" +
            "in\n" +
            "inside\n" +
            "into\n" +
            "like\n" +
            "minus\n" +
            "near\n" +
            "of\n" +
            "off\n" +
            "on\n" +
            "onto\n" +
            "opposite\n" +
            "outside\n" +
            "over\n" +
            "past\n" +
            "per\n" +
            "plus\n" +
            "regarding\n" +
            "round\n" +
            "save\n" +
            "since\n" +
            "than\n" +
            "through\n" +
            "to\n" +
            "toward\n" +
            "towards\n" +
            "under\n" +
            "underneath\n" +
            "unlike\n" +
            "until\n" +
            "up\n" +
            "upon\n" +
            "versus\n" +
            "via\n" +
            "with\n" +
            "within\n" +
            "without";

    public static String [] conjunctionWords = {
            "and",
            "Although",
            "after",
            "though",
            "As",
            "As",
            "Before",
            "because",
            "but",
            "both",
            "either",
            "neither",
            "nor",
            "If",
            "Once",
            "or",
            "Since",
            "So",
            "soon",
            "That",
            "Until",
            "When",
            "Whereas",
            "While",
            "whilst"};


    public static String allAdverbs =
            "aboard\n" +
            "abnormally\n" +
            "about\n" +
            "abroad\n" +
            "absentmindedly\n" +
            "absolutely\n" +
            "abundantly\n" +
            "accidentally\n" +
            "accordingly\n" +
            "actively\n" +
            "actually\n" +
            "acutely\n" +
            "admiringly\n" +
            "affectionately\n" +
            "affirmatively\n" +
            "after\n" +
            "afterwards\n" +
            "agreeably\n" +
            "almost\n" +
            "already\n" +
            "always\n" +
            "amazingly\n" +
            "angrily\n" +
            "annoyingly\n" +
            "annually\n" +
            "anxiously\n" +
            "anyhow\n" +
            "anyplace\n" +
            "anyway\n" +
            "anywhere\n" +
            "appreciably\n" +
            "appropriately\n" +
            "around\n" +
            "arrogantly\n" +
            "aside\n" +
            "assuredly\n" +
            "astonishingly\n" +
            "away\n" +
            "awfully\n" +
            "awkwardly\n" +
            "badly\n" +
            "barely\n" +
            "bashfully\n" +
            "beautifully\n" +
            "before\n" +
            "begrudgingly\n" +
            "believably\n" +
            "bewilderedly\n" +
            "bewilderingly\n" +
            "bitterly\n" +
            "bleakly\n" +
            "blindly\n" +
            "blissfully\n" +
            "boldly\n" +
            "boastfully\n" +
            "boldly\n" +
            "boyishly\n" +
            "bravely\n" +
            "briefly\n" +
            "brightly\n" +
            "brilliantly\n" +
            "briskly\n" +
            "brutally\n" +
            "busily\n" +
            "calmly\n" +
            "candidly\n" +
            "carefully\n" +
            "carelessly\n" +
            "casually\n" +
            "cautiously\n" +
            "certainly\n" +
            "charmingly\n" +
            "cheerfully\n" +
            "chiefly\n" +
            "childishly\n" +
            "cleanly\n" +
            "clearly\n" +
            "cleverly\n" +
            "closely\n" +
            "cloudily\n" +
            "clumsily\n" +
            "coaxingly\n" +
            "coincidentally\n" +
            "coldly\n" +
            "colorfully\n" +
            "commonly\n" +
            "comfortably\n" +
            "compactly\n" +
            "compassionately\n" +
            "completely\n" +
            "confusedly\n" +
            "consequently\n" +
            "considerably\n" +
            "considerately\n" +
            "consistently\n" +
            "constantly\n" +
            "continually\n" +
            "continuously\n" +
            "coolly\n" +
            "correctly\n" +
            "courageously\n" +
            "covertly\n" +
            "cowardly\n" +
            "crazily\n" +
            "crossly\n" +
            "cruelly\n" +
            "cunningly\n" +
            "curiously\n" +
            "currently\n" +
            "customarily\n" +
            "cutely\n" +
            "daily\n" +
            "daintily\n" +
            "dangerously\n" +
            "daringly\n" +
            "darkly\n" +
            "dastardly\n" +
            "dearly\n" +
            "decently\n" +
            "deeply\n" +
            "defiantly\n" +
            "deftly\n" +
            "deliberately\n" +
            "delicately\n" +
            "delightfully\n" +
            "densely\n" +
            "diagonally\n" +
            "differently\n" +
            "diligently\n" +
            "dimly\n" +
            "directly\n" +
            "disorderly\n" +
            "divisively\n" +
            "docilely\n" +
            "dopily\n" +
            "doubtfully\n" +
            "down\n" +
            "dramatically\n" +
            "dreamily\n" +
            "during\n" +
            "eagerly\n" +
            "early\n" +
            "earnestly\n" +
            "easily\n" +
            "efficiently\n" +
            "effortlessly\n" +
            "elaborately\n" +
            "eloquently\n" +
            "elegantly\n" +
            "elsewhere\n" +
            "emotionally\n" +
            "endlessly\n" +
            "energetically\n" +
            "enjoyably\n" +
            "enormously\n" +
            "enough\n" +
            "enthusiastically\n" +
            "entirely\n" +
            "equally\n" +
            "especially\n" +
            "essentially\n" +
            "eternally\n" +
            "ethically\n" +
            "even\n" +
            "evenly\n" +
            "eventually\n" +
            "evermore\n" +
            "every\n" +
            "everywhere\n" +
            "evidently\n" +
            "evocatively\n" +
            "exactly\n" +
            "exceedingly\n" +
            "exceptionally\n" +
            "excitedly\n" +
            "exclusively\n" +
            "explicitly\n" +
            "expressly\n" +
            "extensively\n" +
            "externally\n" +
            "extra\n" +
            "extraordinarily\n" +
            "extremely\n" +
            "fairly\n" +
            "faithfully\n" +
            "famously\n" +
            "far\n" +
            "fashionably\n" +
            "fast\n" +
            "fatally\n" +
            "favorably\n" +
            "ferociously\n" +
            "fervently\n" +
            "fiercely\n" +
            "fiery\n" +
            "finally\n" +
            "financially\n" +
            "finitely\n" +
            "fluently\n" +
            "fondly\n" +
            "foolishly\n" +
            "forever\n" +
            "formally\n" +
            "formerly\n" +
            "fortunately\n" +
            "forward\n" +
            "frankly\n" +
            "frantically\n" +
            "freely\n" +
            "frequently\n" +
            "frenetically\n" +
            "fully\n" +
            "furiously\n" +
            "furthermore\n" +
            "generally\n" +
            "generously\n" +
            "genuinely\n" +
            "gently\n" +
            "genuinely\n" +
            "girlishly\n" +
            "gladly\n" +
            "gleefully\n" +
            "gracefully\n" +
            "graciously\n" +
            "gradually\n" +
            "gratefully\n" +
            "greatly\n" +
            "greedily\n" +
            "grimly\n" +
            "grudgingly\n" +
            "habitually\n" +
            "half-heartedly\n" +
            "handily\n" +
            "handsomely\n" +
            "haphazardly\n" +
            "happily\n" +
            "hastily\n" +
            "harmoniously\n" +
            "harshly\n" +
            "hastily\n" +
            "hatefully\n" +
            "hauntingly\n" +
            "healthily\n" +
            "heartily\n" +
            "heavily\n" +
            "helpfully\n" +
            "hence\n" +
            "highly\n" +
            "hitherto\n" +
            "honestly\n" +
            "hopelessly\n" +
            "horizontally\n" +
            "hourly\n" +
            "how\n" +
            "however\n" +
            "hugely\n" +
            "humorously\n" +
            "hungrily\n" +
            "hurriedly\n" +
            "hysterically\n" +
            "icily\n" +
            "identifiably\n" +
            "idiotically\n" +
            "imaginatively\n" +
            "immeasurably\n" +
            "immediately\n" +
            "immensely\n" +
            "impatiently\n" +
            "impressively\n" +
            "inappropriately\n" +
            "incessantly\n" +
            "incorrectly\n" +
            "indeed\n" +
            "independently\n" +
            "indoors\n" +
            "indubitably\n" +
            "inevitably\n" +
            "infinitely\n" +
            "informally\n" +
            "infrequently\n" +
            "innocently\n" +
            "inquisitively\n" +
            "instantly\n" +
            "intelligently\n" +
            "intensely\n" +
            "intently\n" +
            "interestingly\n" +
            "intermittently\n" +
            "internally\n" +
            "invariably\n" +
            "invisibly\n" +
            "inwardly\n" +
            "ironically\n" +
            "irrefutably\n" +
            "irritably\n" +
            "jaggedly\n" +
            "jauntily\n" +
            "jealously\n" +
            "jovially\n" +
            "joyfully\n" +
            "joylessly\n" +
            "joyously\n" +
            "jubilantly\n" +
            "judgmentally\n" +
            "just\n" +
            "justly\n" +
            "keenly\n" +
            "kiddingly\n" +
            "kindheartedly\n" +
            "kindly\n" +
            "knavishly\n" +
            "knottily\n" +
            "knowingly\n" +
            "knowledgeably\n" +
            "kookily\n" +
            "lastly\n" +
            "late\n" +
            "lately\n" +
            "later\n" +
            "lazily\n" +
            "less\n" +
            "lightly\n" +
            "likely\n" +
            "limply\n" +
            "lithely\n" +
            "lively\n" +
            "loftily\n" +
            "longingly\n" +
            "loosely\n" +
            "loudly\n" +
            "lovingly\n" +
            "loyally\n" +
            "luckily\n" +
            "luxuriously\n" +
            "madly\n" +
            "magically\n" +
            "mainly\n" +
            "majestically\n" +
            "markedly\n" +
            "materially\n" +
            "meaningfully\n" +
            "meanly\n" +
            "meantime\n" +
            "meanwhile\n" +
            "measurably\n" +
            "mechanically\n" +
            "medically\n" +
            "menacingly\n" +
            "merely\n" +
            "merrily\n" +
            "methodically\n" +
            "mightily\n" +
            "miserably\n" +
            "mockingly\n" +
            "monthly\n" +
            "morally\n" +
            "more\n" +
            "moreover\n" +
            "mortally\n" +
            "mostly\n" +
            "much\n" +
            "mysteriously\n" +
            "nastily\n" +
            "naturally\n" +
            "naughtily\n" +
            "nearby\n" +
            "nearly\n" +
            "neatly\n" +
            "needily\n" +
            "negatively\n" +
            "nervously\n" +
            "never\n" +
            "nevertheless\n" +
            "next\n" +
            "nicely\n" +
            "nightly\n" +
            "noisily\n" +
            "normally\n" +
            "nosily\n" +
            "not\n" +
            "now\n" +
            "nowadays\n" +
            "numbly\n" +
            "obediently\n" +
            "obligingly\n" +
            "obnoxiously\n" +
            "obviously\n" +
            "occasionally\n" +
            "oddly\n" +
            "offensively\n" +
            "officially\n" +
            "often\n" +
            "ominously\n" +
            "once\n" +
            "only\n" +
            "openly\n" +
            "optimistically\n" +
            "orderly\n" +
            "ordinarily\n" +
            "outdoors\n" +
            "outrageously\n" +
            "outwardly\n" +
            "outwards\n" +
            "overconfidently\n" +
            "overseas\n" +
            "painfully\n" +
            "painlessly\n" +
            "paradoxically\n" +
            "partially\n" +
            "particularly\n" +
            "passionately\n" +
            "patiently\n" +
            "perfectly\n" +
            "periodically\n" +
            "perpetually\n" +
            "persistently\n" +
            "personally\n" +
            "persuasively\n" +
            "physically\n" +
            "plainly\n" +
            "playfully\n" +
            "poetically\n" +
            "poignantly\n" +
            "politely\n" +
            "poorly\n" +
            "positively\n" +
            "possibly\n" +
            "potentially\n" +
            "powerfully\n" +
            "presently\n" +
            "presumably\n" +
            "prettily\n" +
            "previously\n" +
            "primly\n" +
            "principally\n" +
            "probably\n" +
            "promptly\n" +
            "properly\n" +
            "proudly\n" +
            "punctually\n" +
            "puzzlingly\n" +
            "quaintly\n" +
            "queasily\n" +
            "questionably\n" +
            "questioningly\n" +
            "quicker\n" +
            "quickly\n" +
            "quietly\n" +
            "quirkily\n" +
            "quite\n" +
            "quizzically\n" +
            "randomly\n" +
            "rapidly\n" +
            "rarely\n" +
            "readily\n" +
            "really\n" +
            "reasonably\n" +
            "reassuringly\n" +
            "recently\n" +
            "recklessly\n" +
            "regularly\n" +
            "reliably\n" +
            "reluctantly\n" +
            "remarkably\n" +
            "repeatedly\n" +
            "reproachfully\n" +
            "reponsibly\n" +
            "resentfully\n" +
            "respectably\n" +
            "respectfully\n" +
            "restfully\n" +
            "richly\n" +
            "ridiculously\n" +
            "righteously\n" +
            "rightfully\n" +
            "rightly\n" +
            "rigidly\n" +
            "roughly\n" +
            "routinely\n" +
            "rudely\n" +
            "ruthlessly\n" +
            "sadly\n" +
            "safely\n" +
            "scarcely\n" +
            "scarily\n" +
            "scientifically\n" +
            "searchingly\n" +
            "secretively\n" +
            "securely\n" +
            "sedately\n" +
            "seemingly\n" +
            "seldom\n" +
            "selfishly\n" +
            "selflessly\n" +
            "separately\n" +
            "seriously\n" +
            "shakily\n" +
            "shamelessly\n" +
            "sharply\n" +
            "sheepishly\n" +
            "shoddily\n" +
            "shortly\n" +
            "shrilly\n" +
            "significantly\n" +
            "silently\n" +
            "simply\n" +
            "sincerely\n" +
            "singularly\n" +
            "shyly\n" +
            "skillfully\n" +
            "sleepily\n" +
            "slightly\n" +
            "slowly\n" +
            "slyly\n" +
            "smoothly\n" +
            "so\n" +
            "softly\n" +
            "solely\n" +
            "solemnly\n" +
            "solidly\n" +
            "silicitiously\n" +
            "somehow\n" +
            "sometimes\n" +
            "somewhat\n" +
            "somewhere\n" +
            "soon\n" +
            "specially\n" +
            "specifically\n" +
            "spectacularly\n" +
            "speedily\n" +
            "spiritually\n" +
            "splendidly\n" +
            "sporadically\n" +
            "spasmodically\n" +
            "startlingly\n" +
            "steadily\n" +
            "stealthily\n" +
            "sternly\n" +
            "still\n" +
            "strenuously\n" +
            "stressfully\n" +
            "strictly\n" +
            "structurally\n" +
            "studiously\n" +
            "stupidly\n" +
            "stylishly\n" +
            "subsequently\n" +
            "substantially\n" +
            "subtly\n" +
            "successfully\n" +
            "suddenly\n" +
            "sufficiently\n" +
            "suitably\n" +
            "superficially\n" +
            "supremely\n" +
            "surely\n" +
            "surprisingly\n" +
            "suspiciously\n" +
            "sweetly\n" +
            "swiftly\n" +
            "sympathetically\n" +
            "systematically\n" +
            "temporarily\n" +
            "tenderly\n" +
            "tensely\n" +
            "tepidly\n" +
            "terribly\n" +
            "thankfully\n" +
            "then\n" +
            "there\n" +
            "thereby\n" +
            "thoroughly\n" +
            "thoughtfully\n" +
            "thus\n" +
            "tightly\n" +
            "today\n" +
            "together\n" +
            "tomorrow\n" +
            "too\n" +
            "totally\n" +
            "touchingly\n" +
            "tremendously\n" +
            "truly\n" +
            "truthfully\n" +
            "twice\n" +
            "ultimately\n" +
            "unabashedly\n" +
            "unanimously\n" +
            "unbearably\n" +
            "unbelievably\n" +
            "unemotionally\n" +
            "unethically\n" +
            "unexpectedly\n" +
            "unfailingly\n" +
            "unfavorably\n" +
            "unfortunately\n" +
            "uniformly\n" +
            "unilaterally\n" +
            "unimpressively\n" +
            "universally\n" +
            "unnaturally\n" +
            "unnecessarily\n" +
            "unquestionably\n" +
            "unwillingly\n" +
            "up\n" +
            "upbeat\n" +
            "unkindly\n" +
            "upliftingly\n" +
            "upright\n" +
            "unselfishly\n" +
            "upside-down\n" +
            "unskillfully\n" +
            "upward\n" +
            "upwardly\n" +
            "urgently\n" +
            "usefully\n" +
            "uselessly\n" +
            "usually\n" +
            "utterly\n" +
            "vacantly\n" +
            "vaguely\n" +
            "vainly\n" +
            "valiantly\n" +
            "vastly\n" +
            "verbally\n" +
            "vertically\n" +
            "very\n" +
            "viciously\n" +
            "victoriously\n" +
            "vigilantly\n" +
            "vigorously\n" +
            "violently\n" +
            "visibly\n" +
            "visually\n" +
            "vivaciously\n" +
            "voluntarily\n" +
            "warmly\n" +
            "weakly\n" +
            "wearily\n" +
            "weekly\n" +
            "well\n" +
            "wetly\n" +
            "when\n" +
            "where\n" +
            "while\n" +
            "whole-heartedly\n" +
            "wholly\n" +
            "why\n" +
            "wickedly\n" +
            "widely\n" +
            "wiggly\n" +
            "wildly\n" +
            "willfully\n" +
            "willingly\n" +
            "wisely\n" +
            "woefully\n" +
            "wonderfully\n" +
            "worriedly\n" +
            "worthily\n" +
            "wrongly\n" +
            "yearly\n" +
            "yearningly\n" +
            "yesterday\n" +
            "yet\n" +
            "youthfully\n" +
            "zanily\n" +
            "zealously\n" +
            "zestfully\n" +
            "zestily";

    public static String [] stopWordsStringArray = {"a's", "able", "about", "above", "according", "accordingly", "across", "actually", "after", "afterwards", "again", "against", "ain't", "all", "allow", "allows", "almost", "alone", "along", "already", "also", "although", "always", "am", "among", "amongst", "an", "and", "another", "any", "anybody", "anyhow", "anyone", "anything", "anyway", "anyways", "anywhere", "apart", "appear", "appreciate", "appropriate", "are", "aren't", "around", "as", "aside", "ask", "asking", "associated", "at", "available", "away", "awfully",
            "be", "became", "because", "become", "becomes", "becoming", "been", "before", "beforehand", "behind", "being", "believe", "below", "beside", "besides", "best", "better", "between", "beyond", "both", "brief", "but", "by",
            "c'mon", "c's", "came", "can", "can't", "cannot", "cant", "cause", "causes", "certain", "certainly", "changes", "clearly", "co", "com", "come", "comes", "concerning", "consequently", "consider", "considering", "contain", "containing", "contains", "corresponding", "could", "couldn't", "course", "currently",
            "definitely", "described", "despite", "did", "didn't", "different", "do", "does", "doesn't", "doing", "don't", "done", "down", "downwards", "during",
            "each", "edu", "eg", "eight", "either", "else", "elsewhere", "enough", "entirely", "especially", "et", "etc", "even", "ever", "every", "everybody", "everyone", "everything", "everywhere", "ex", "exactly", "example", "except",
            "far", "few", "fifth", "first", "five", "followed", "following", "follows", "for", "former", "formerly", "forth", "four", "from", "further", "furthermore",
            "get", "gets", "getting", "given", "gives", "go", "goes", "going", "gone", "got", "gotten", "greetings",
            "had", "hadn't", "happens", "hardly", "has", "hasn't", "have", "haven't", "having", "he", "he's", "hello", "help", "hence", "her", "here", "here's", "hereafter", "hereby", "herein", "hereupon", "hers", "herself", "hi", "him", "himself", "his", "hither", "hopefully", "how", "howbeit", "however",
            "i'd", "i'll", "i'm", "i've", "ie", "if", "ignored", "immediate", "in", "inasmuch", "inc", "indeed", "indicate", "indicated", "indicates", "inner", "insofar", "instead", "into", "inward", "is", "isn't", "it", "it'd", "it'll", "it's", "its", "itself",
            "just",
            "keep", "keeps", "kept", "know", "known", "knows",
            "last", "lately", "later", "latter", "latterly", "least", "less", "lest", "let", "let's", "like", "liked", "likely", "little", "look", "looking", "looks", "ltd",
            "mainly", "many", "may", "maybe", "me", "mean", "meanwhile", "merely", "might", "more", "moreover", "most", "mostly", "much", "must", "my", "myself",
            "name", "namely", "nd", "near", "nearly", "necessary", "need", "needs", "neither", "never", "nevertheless", "new", "next", "nine", "no", "nobody", "non", "none", "noone", "nor", "normally", "not", "nothing", "novel", "now", "nowhere",
            "obviously", "of", "off", "often", "oh", "ok", "okay", "old", "on", "once", "one", "ones", "only", "onto", "or", "other", "others", "otherwise", "ought", "our", "ours", "ourselves", "out", "outside", "over", "overall", "own",
            "particular", "particularly", "per", "perhaps", "placed", "please", "plus", "possible", "presumably", "probably", "provides", "que", "quite", "qv", "rather", "rd", "re", "really", "reasonably", "regarding", "regardless", "regards", "relatively", "respectively", "right", "said", "same", "saw", "say", "saying", "says", "second", "secondly", "see", "seeing", "seem", "seemed", "seeming", "seems", "seen", "self", "selves", "sensible", "sent", "serious", "seriously", "seven", "several", "shall", "she", "should", "shouldn't", "since", "six", "so", "some", "somebody", "somehow", "someone", "something", "sometime", "sometimes", "somewhat", "somewhere", "soon", "sorry", "specified", "specify", "specifying", "still", "sub", "such", "sup", "sure", "t's", "take", "taken", "tell", "tends", "th", "than", "thank", "thanks", "thanx", "that", "that's", "thats", "the", "their", "theirs", "them", "themselves", "then", "thence", "there", "there's", "thereafter", "thereby", "therefore", "therein", "theres", "thereupon", "these", "they", "they'd", "they'll", "they're", "they've", "think", "third", "this", "thorough", "thoroughly", "those", "though", "three", "through", "throughout", "thru", "thus", "to", "together", "too", "took", "toward", "towards", "tried", "tries", "truly", "try", "trying", "twice", "two", "un", "under", "unfortunately", "unless", "unlikely", "until", "unto", "up", "upon", "us", "use", "used", "useful", "uses", "using", "usually", "value", "various", "very", "via", "viz", "vs", "want", "wants", "was", "wasn't", "way", "we", "we'd", "we'll", "we're", "we've", "welcome", "well", "went", "were", "weren't", "what", "what's", "whatever", "when", "whence", "whenever", "where", "where's", "whereafter", "whereas", "whereby", "wherein", "whereupon", "wherever", "whether", "which", "while", "whither", "who", "who's", "whoever", "whole", "whom", "whose", "why", "will", "willing", "wish", "with", "within", "without", "won't", "wonder", "would", "wouldn't", "yes", "yet", "you", "you'd", "you'll", "you're", "you've", "your", "yours", "yourself", "yourselves", "zero"};


}